### ISSUE TITLE
provider opens more than one connection at a time

### ISSUE THREAD

**Issue by Hades32** [danthegoodman1/frontlink#9]
![image](https://github.com/user-attachments/assets/b1e8afae-f80f-4c38-8941-79f98549ff67)

This
https://github.com/danthegoodman1/frontlink/blob/55668134ab238df9e7b6f1ed48700a4a82a45eb4/src/provider.tsx#L218-L220
and the setTimeout (and maybe more) should happen in useEffect

**Comment by danthegoodman1** [comment]
I'm not able to recreate this, even running locally (to try and get react to double render).

Discussion happened in internal slack, since this original description is not very clear, that the connection code being outside of the useEffect could be causing this.
